In [2]:
# --- STEP 1: 5-FOLD STRATIFIED CV GAIN SCREENING (FULL DATASET) ---

import os
import time
import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import StratifiedKFold

start_time = time.time()
print("🚀 [STEP 1] Bắt đầu đánh giá Feature Importance (Gain) bằng 5-Fold CV...")

# 1. Nạp Master Dataset V2
master_path = '/Users/nguyenminhtri/FinalYearPro/data/processed/master_train_dataset_v2.parquet'
print(f"⏳ Đang nạp toàn bộ Master Dataset từ: {master_path}")
df_master = pd.read_parquet(master_path)

drop_cols = ['SK_ID_CURR', 'TARGET']
feature_cols = [c for c in df_master.columns if c not in drop_cols]

X = df_master[feature_cols].copy()
y = df_master['TARGET']

# Ép kiểu category cho toàn bộ cột chuỗi (string/object)
cat_cols = X.select_dtypes(include=['object', 'category', 'string']).columns.tolist()
if cat_cols:
    print(f"💡 Đã chuyển đổi {len(cat_cols)} cột văn bản sang kiểu 'category'.")
    for col in cat_cols:
        X[col] = X[col].astype('category')

total_rows, total_cols = X.shape
print(f"📊 Dữ liệu đầu vào: {total_rows:,} dòng | {total_cols} thuộc tính")
print("-" * 80)

# 2. Khởi tạo Stratified 5-Fold Cross-Validation
N_SPLITS = 5
skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

feature_importances_gain = np.zeros(total_cols)
trained_models = []  # Lưu lại 5 models để dùng tiếp cho Step 2 nếu cần

# 3. Vòng lặp 5-Fold CV
for fold, (train_idx, val_idx) in enumerate(skf.split(X, y), 1):
    fold_start = time.time()
    print(f"⏳ [Fold {fold}/{N_SPLITS}] Đang huấn luyện LightGBM...")

    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]

    model = lgb.LGBMClassifier(
        n_estimators=1000,
        learning_rate=0.05,
        num_leaves=31,
        random_state=42 + fold,
        n_jobs=-1,
        importance_type='gain'
    )

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=False)]
    )

    feature_importances_gain += model.feature_importances_ / N_SPLITS
    trained_models.append((model, val_idx))

    print(f"   ✓ Fold {fold} hoàn tất trong: {time.time() - fold_start:.2f} giây")

# 4. Tổng hợp bảng xếp hạng Gain
df_gain_ranking = pd.DataFrame({
    'feature': feature_cols,
    'mean_gain': feature_importances_gain
}).sort_values('mean_gain', ascending=False).reset_index(drop=True)

zero_imp_df = df_gain_ranking[df_gain_ranking['mean_gain'] == 0]
useful_imp_df = df_gain_ranking[df_gain_ranking['mean_gain'] > 0]
zero_importance_cols = zero_imp_df['feature'].tolist()

# Xuất file kết quả Step 1
output_step1_path = '/Users/nguyenminhtri/FinalYearPro/data/processed/feature_gain_ranking_5fold.csv'
os.makedirs(os.path.dirname(output_step1_path), exist_ok=True)
df_gain_ranking.to_csv(output_step1_path, index=False)

print("=" * 80)
print(f"🎉 HOÀN TẤT STEP 1 CẢ 5-FOLD CV TRONG: {time.time() - start_time:.2f} GIÂY")
print(f"💾 Kết quả Gain đã lưu tại: {output_step1_path}")
print(f"✅ Số lượng cột CÓ ĐÓNG GÓP (Mean Gain > 0) : {len(useful_imp_df):,} cột")
print(f"❌ Số lượng cột NHIỄU / THỪA (Mean Gain == 0): {len(zero_importance_cols):,} cột")
print("=" * 80)

# In danh sách code Python để copy xóa
print("\n" + "=" * 80)
print(f"📌 DANH SÁCH {len(zero_importance_cols)} CỘT BỊ 0 ĐIỂM GAIN (COPY ĐỂ DROP):")
print("=" * 80)
print("zero_importance_cols = [")
for col in zero_importance_cols:
    print(f"    '{col}',")
print("]")

🚀 [STEP 1] Bắt đầu đánh giá Feature Importance (Gain) bằng 5-Fold CV...
⏳ Đang nạp toàn bộ Master Dataset từ: /Users/nguyenminhtri/FinalYearPro/data/processed/master_train_dataset_v2.parquet
💡 Đã chuyển đổi 6 cột văn bản sang kiểu 'category'.
📊 Dữ liệu đầu vào: 307,511 dòng | 1030 thuộc tính
--------------------------------------------------------------------------------
⏳ [Fold 1/5] Đang huấn luyện LightGBM...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226148
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.163600 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 162742
[LightGBM] [Info] Number of data points in the train set: 246008, number of used features: 1029
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432482
[LightGBM] [Info] Start training from score -2.432482
   ✓ Fold 1 hoàn tất trong: 36.01 giây
⏳ [Fold 2/5] Đang huấn luyện LightGBM...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.144308 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 162696
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 1029
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
   ✓ Fold 2 hoàn tất trong: 38.40 giây
⏳ [Fold 3/5] Đang huấn luyện LightGBM...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.180171 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 162665
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 1029
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
   ✓ Fold 3 hoàn tất trong: 32.91 giây
⏳ [Fold 4/5] Đang huấn luyện LightGBM...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.186567 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 162755
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 1029
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
   ✓ Fold 4 hoàn tất trong: 39.76 giây
⏳ [Fold 5/5] Đang huấn luyện LightGBM...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.185115 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 162703
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 1029
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
   ✓ Fold 5 hoàn tất trong: 35.41 giây
================================================================================
🎉 HOÀN TẤT STEP 1 CẢ 5-FOLD CV TRONG: 186.96 GIÂY
💾 Kết quả Gain đã lưu tại: /Users/nguyenminhtri/FinalYearPro/data/processed/feature_gain_ranking_5fold.csv
✅ Số lượng cột CÓ ĐÓNG GÓP (Mean Gain > 0) : 876 cột
❌ Số lượng cột NHIỄU / THỪA (Mean Gain == 0): 154 cột
================================================================================

================================================================================
📌 DANH SÁCH 154 CỘT BỊ 0 ĐIỂM GAIN (COPY ĐỂ DROP):
================================================================================
zero_importance_cols = [
    'CC_AMT_DRAWINGS_POS_IS_NA_MEAN',
    'BUREAU_CNT_CREDIT_PROLONG_MAX',
    'CC_STATUS_IS_COMPLETED_LAST',
    'CC_CNT_INSTALMENT_MATURE_IS_NA_SUM',
    'DAYS_EMPLOYED_CLEAN',
    'CC_AMT_TOTAL_RECEIVABLE_MEAN',
    'CC_CNT_INSTALMENT_MATURE_IS_NA_MEAN',
    'CC_IS_DPD_MAX',
    'CC_AMT_DRAWINGS_POS_IS_NA_SUM',
    'CC_IS_UNDERPAID_MIN_MAX',
    'CC_IS_DPD_90_MAX',
    'BUREAU_CNT_CREDIT_PROLONG_SUM',
    'CC_IS_DPD_30_MAX',
    'CC_IS_MATURE_ACCOUNT_LAST',
    'DAYS_EMPLOYED_ANOM',
    'BUREAU_IS_BAD_DEBT_SUM',
    'BUREAU_CLOSED_IS_OVER_LIMIT_SUM',
    'CC_AMT_BALANCE_POS_MAX',
    'BUREAU_CLOSED_IS_BAD_DEBT_SUM',
    'BUREAU_CLOSED_OVERDUE_TO_DEBT_RATIO_MEAN',
    'BUREAU_CLOSED_IS_CLOSED_MEAN',
    'BUREAU_CLOSED_IS_ACTIVE_SUM',
    'BUREAU_CLOSED_IS_ACTIVE_MEAN',
    'BUREAU_CLOSED_IS_SOLD_SUM',
    'BUREAU_CLOSED_IS_SOLD_MEAN',
    'BUREAU_CLOSED_IS_BAD_DEBT_MEAN',
    'BUREAU_ACTIVE_IS_MULTIPLE_PROLONGED_SUM',
    'BUREAU_CLOSED_IS_BAD_OR_SOLD_SUM',
    'BUREAU_CLOSED_IS_BAD_OR_SOLD_MEAN',
    'PREV_AMT_GOODS_PRICE_SUM',
    'BUREAU_CLOSED_IS_OVERDUE_SUM',
    'BUREAU_CLOSED_IS_OVERDUE_MEAN',
    'BUREAU_CLOSED_DPD_GR2_SUM',
    'BUREAU_CLOSED_CNT_CREDIT_PROLONG_MAX',
    'PREV_CNT_PAYMENT_IS_NA_MEAN',
    'PREV_CNT_PAYMENT_IS_NA_SUM',
    'BUREAU_CLOSED_CNT_CREDIT_PROLONG_SUM',
    'PREV_CNT_PAYMENT_SUM',
    'BUREAU_CLOSED_CREDIT_DAY_OVERDUE_MEAN',
    'BUREAU_CLOSED_CREDIT_DAY_OVERDUE_MAX',
    'BUREAU_CLOSED_AMT_CREDIT_SUM_OVERDUE_MAX',
    'BUREAU_ACTIVE_LOAN_COUNT',
    'BUREAU_ACTIVE_UPDATE_ANOM_MEAN',
    'BUREAU_ACTIVE_UPDATE_ANOM_SUM',
    'BUREAU_ACTIVE_TYPE_Other_SUM',
    'BUREAU_ACTIVE_TYPE_Mortgage_SUM',
    'BUREAU_ACTIVE_TYPE_Car loan_SUM',
    'BUREAU_ACTIVE_HAS_SUM_OVERDUE_MEAN',
    'BUREAU_ACTIVE_HAS_SUM_OVERDUE_SUM',
    'BUREAU_ACTIVE_IS_OVER_LIMIT_SUM',
    'BUREAU_CLOSED_DPD_GR2_MEAN',
    'BUREAU_CLOSED_DPD_GR3_SUM',
    'BUREAU_CLOSED_DPD_GR3_MEAN',
    'BB_STATUS_5_SUM_MAX',
    'BUREAU_CLOSED_HAS_AVAILABLE_LIMIT_SUM',
    'BUREAU_CLOSED_HAS_SUM_OVERDUE_SUM',
    'BUREAU_CLOSED_TYPE_Mortgage_SUM',
    'BUREAU_CLOSED_TYPE_Other_SUM',
    'BUREAU_CLOSED_TYPE_Other_MEAN',
    'BUREAU_CLOSED_UPDATE_ANOM_SUM',
    'BUREAU_CLOSED_UPDATE_ANOM_MEAN',
    'BUREAU_CLOSED_UPDATED_RECENT_30D_SUM',
    'BUREAU_CLOSED_LOAN_COUNT',
    'BB_STATUS_2_SUM_MAX',
    'BB_STATUS_3_SUM_SUM',
    'BB_STATUS_3_SUM_MAX',
    'BB_STATUS_4_SUM_SUM',
    'BB_STATUS_4_SUM_MAX',
    'BB_STATUS_5_MEAN_MAX',
    'BUREAU_CLOSED_DPD_GR4_SUM',
    'BUREAU_CLOSED_IS_MULTIPLE_PROLONGED_SUM',
    'BUREAU_CLOSED_IS_PROLONGED_MEAN',
    'BB_IS_NPL_90PLUS_SUM_MAX',
    'BUREAU_CLOSED_IS_PROLONGED_SUM',
    'BUREAU_CLOSED_FACT_ANOM_MEAN',
    'BUREAU_CLOSED_FACT_ANOM_SUM',
    'BUREAU_CLOSED_IS_NPL_MEAN',
    'PREV_AMT_APPLICATION_MIN',
    'BUREAU_CLOSED_IS_NPL_SUM',
    'BUREAU_CLOSED_DPD_GR5_MEAN',
    'PREV_AMT_CREDIT_MAX',
    'PREV_AMT_CREDIT_MIN',
    'BUREAU_CLOSED_DPD_GR5_SUM',
    'BUREAU_CLOSED_DPD_GR4_MEAN',
    'BUREAU_ACTIVE_IS_MULTIPLE_PROLONGED_MEAN',
    'BUREAU_ACTIVE_IS_PROLONGED_SUM',
    'BUREAU_IS_BAD_DEBT_MEAN',
    'BUREAU_UPDATE_ANOM_SUM',
    'POS_STATUS_Canceled_SUM',
    'POS_STATUS_Canceled_MEAN',
    'POS_STATUS_Approved_SUM',
    'POS_STATUS_Amortized_debt_SUM',
    'POS_STATUS_Amortized_debt_MEAN',
    'BUREAU_TYPE_Other_SUM',
    'BUREAU_UPDATE_ANOM_MEAN',
    'BUREAU_ACTIVE_IS_LATE_SETTLED_SUM',
    'BUREAU_ACTIVE_DAYS_ENDDATE_FACT_CLEAN_MEAN',
    'BUREAU_ACTIVE_SETTLEMENT_DIFF_DAYS_MEAN',
    'POS_IS_DPD_DEF_90_SUM',
    'POS_IS_DPD_DEF_90_MEAN',
    'POS_IS_DPD_DEF_60_SUM',
    'POS_IS_DPD_DEF_60_MEAN',
    'POS_STATUS_XNA_MEAN',
    'POS_STATUS_XNA_SUM',
    'BUREAU_IS_MULTIPLE_PROLONGED_MEAN',
    'BUREAU_IS_MULTIPLE_PROLONGED_SUM',
    'BUREAU_IS_PROLONGED_SUM',
    'BUREAU_FACT_ANOM_MEAN',
    'BUREAU_FACT_ANOM_SUM',
    'BUREAU_IS_NPL_MEAN',
    'BUREAU_IS_NPL_SUM',
    'BUREAU_DPD_GR5_MEAN',
    'BUREAU_DPD_GR5_SUM',
    'BUREAU_DPD_GR4_MEAN',
    'BUREAU_DPD_GR4_SUM',
    'BUREAU_DPD_GR3_SUM',
    'BUREAU_DPD_GR2_SUM',
    'BUREAU_IS_OVERDUE_SUM',
    'BUREAU_IS_BAD_OR_SOLD_SUM',
    'POS_IS_DPD_DEF_30_SUM',
    'POS_IS_DPD_60_SUM',
    'BUREAU_ACTIVE_CNT_CREDIT_PROLONG_MAX',
    'PREV_RATE_DOWN_PAYMENT_IS_NA_SUM',
    'BUREAU_ACTIVE_FACT_ANOM_MEAN',
    'BUREAU_ACTIVE_FACT_ANOM_SUM',
    'PREV_NAME_CONTRACT_TYPE_XNA_MEAN',
    'PREV_NAME_CONTRACT_TYPE_XNA_SUM',
    'PREV_NAME_CONTRACT_TYPE_nan_MAX',
    'PREV_NAME_CONTRACT_TYPE_nan_MEAN',
    'PREV_NAME_CONTRACT_TYPE_nan_MIN',
    'PREV_NAME_CONTRACT_TYPE_nan_SUM',
    'PREV_NAME_CONTRACT_TYPE_nan_VAR',
    'BUREAU_CLOSED_IS_OVER_LIMIT_MEAN',
    'BUREAU_ACTIVE_IS_NPL_SUM',
    'BUREAU_ACTIVE_DPD_GR5_MEAN',
    'BUREAU_ACTIVE_DPD_GR5_SUM',
    'PREV_RATE_DOWN_PAYMENT_IS_NA_MEAN',
    'PREV_RATE_INTEREST_PRIVILEGED_IS_NA_MEAN',
    'POS_DPD_TREND_6M_12M_MAX',
    'PREV_RATE_INTEREST_PRIVILEGED_IS_NA_SUM',
    'BUREAU_ACTIVE_DPD_GR3_SUM',
    'BUREAU_ACTIVE_DPD_GR2_SUM',
    'BUREAU_ACTIVE_IS_OVERDUE_SUM',
    'BUREAU_ACTIVE_IS_BAD_OR_SOLD_MEAN',
    'BUREAU_ACTIVE_IS_BAD_OR_SOLD_SUM',
    'BUREAU_ACTIVE_IS_BAD_DEBT_MEAN',
    'BUREAU_ACTIVE_IS_BAD_DEBT_SUM',
    'BUREAU_ACTIVE_IS_SOLD_MEAN',
    'BUREAU_ACTIVE_IS_SOLD_SUM',
    'BUREAU_ACTIVE_IS_ACTIVE_MEAN',
    'POS_DPD_IS_DETERIORATING_SUM',
    'BUREAU_ACTIVE_IS_CLOSED_MEAN',
    'BUREAU_ACTIVE_IS_CLOSED_SUM',
    'BUREAU_ACTIVE_IS_NPL_MEAN',
]

In [4]:
# --- STEP 2: 5-FOLD STRATIFIED CV TREESHAP EVALUATION (FIXED SHAPE ERROR) ---

import os
import time
import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import StratifiedKFold
import shap

start_time = time.time()
print("🚀 [STEP 2] Bắt đầu tính toán TreeSHAP Values trên tập cột có Gain > 0...")

# 1. Lọc dữ liệu chỉ giữ lại các cột có Gain > 0 từ Step 1
valid_features = useful_imp_df['feature'].tolist()
X_filtered = X[valid_features].copy()

total_rows, total_cols = X_filtered.shape
print(f"📊 Tập thuộc tính đưa vào SHAP: {total_cols} cột (Đã cắt bỏ {len(zero_importance_cols)} cột nhiễu)")
print("-" * 80)

# 2. Khởi tạo 5-Fold CV mới cho tập thuộc tính đã rút gọn
N_SPLITS = 5
skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

shap_importances_mean = np.zeros(total_cols)

# 3. Vòng lặp huấn luyện & tính SHAP trực tiếp trên tập thuộc tính sạch
for fold, (train_idx, val_idx) in enumerate(skf.split(X_filtered, y), 1):
    fold_start = time.time()
    print(f"⏳ [Fold {fold}/{N_SPLITS}] Huấn luyện mô hình tinh gọn & Tính TreeSHAP...")

    X_train, y_train = X_filtered.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X_filtered.iloc[val_idx], y.iloc[val_idx]

    # Model LightGBM huấn luyện riêng trên tập cột đã lọc sạch
    model_clean = lgb.LGBMClassifier(
        n_estimators=1000,
        learning_rate=0.05,
        num_leaves=31,
        random_state=42 + fold,
        n_jobs=-1,
        importance_type='gain'
    )

    model_clean.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=False)]
    )

    # Lấy mẫu 3,000 khách hàng/fold để tính SHAP an toàn bộ nhớ RAM
    X_val_sample = X_val.sample(n=min(3000, len(X_val)), random_state=42)

    explainer = shap.TreeExplainer(model_clean)
    shap_vals = explainer.shap_values(X_val_sample)

    if isinstance(shap_vals, list):
        shap_vals = shap_vals[1]

    shap_importances_mean += np.abs(shap_vals).mean(axis=0) / N_SPLITS
    print(f"   ✓ Fold {fold} SHAP hoàn tất trong: {time.time() - fold_start:.2f} giây")

# 4. Gộp điểm Mean Gain (Step 1) và Mean Abs SHAP (Step 2)
df_final_ranking = useful_imp_df.copy()
df_final_ranking['mean_abs_shap'] = shap_importances_mean
df_final_ranking = df_final_ranking.sort_values('mean_abs_shap', ascending=False).reset_index(drop=True)

# 5. Xuất file xếp hạng tổng hợp
output_step2_path = '/Users/nguyenminhtri/FinalYearPro/data/processed/feature_ranking_5fold_shap.csv'
os.makedirs(os.path.dirname(output_step2_path), exist_ok=True)
df_final_ranking.to_csv(output_step2_path, index=False)

print("=" * 80)
print(f"🎉 HOÀN TẤT STEP 2 SHAP RANKING TRONG: {time.time() - start_time:.2f} GIÂY")
print(f"💾 File xếp hạng đầy đủ (Gain + SHAP) đã lưu tại: {output_step2_path}")
print(f"📊 Tổng số thuộc tính được chấm điểm SHAP: {len(df_final_ranking):,} cột")
print("=" * 80)

print("\n📋 TOP 50 CỘT CÓ ĐIỂM SHAP CAO NHẤT TỪ 5-FOLD CV:")
display(df_final_ranking.head(50))

🚀 [STEP 2] Bắt đầu tính toán TreeSHAP Values trên tập cột có Gain > 0...
📊 Tập thuộc tính đưa vào SHAP: 876 cột (Đã cắt bỏ 154 cột nhiễu)
--------------------------------------------------------------------------------
⏳ [Fold 1/5] Huấn luyện mô hình tinh gọn & Tính TreeSHAP...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226148
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.192369 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 157525
[LightGBM] [Info] Number of data points in the train set: 246008, number of used features: 876
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432482
[LightGBM] [Info] Start training from score -2.432482

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

   ✓ Fold 1 SHAP hoàn tất trong: 36.21 giây
⏳ [Fold 2/5] Huấn luyện mô hình tinh gọn & Tính TreeSHAP...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.181985 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 157499
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 876
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

   ✓ Fold 2 SHAP hoàn tất trong: 40.02 giây
⏳ [Fold 3/5] Huấn luyện mô hình tinh gọn & Tính TreeSHAP...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.269560 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 157467
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 876
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

   ✓ Fold 3 SHAP hoàn tất trong: 33.35 giây
⏳ [Fold 4/5] Huấn luyện mô hình tinh gọn & Tính TreeSHAP...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.158188 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 157546
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 876
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

   ✓ Fold 4 SHAP hoàn tất trong: 41.08 giây
⏳ [Fold 5/5] Huấn luyện mô hình tinh gọn & Tính TreeSHAP...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.137528 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 157500
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 876
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
   ✓ Fold 5 SHAP hoàn tất trong: 35.64 giây
================================================================================
🎉 HOÀN TẤT STEP 2 SHAP RANKING TRONG: 189.49 GIÂY
💾 File xếp hạng đầy đủ (Gain + SHAP) đã lưu tại: /Users/nguyenminhtri/FinalYearPro/data/processed/feature_ranking_5fold_shap.csv
📊 Tổng số thuộc tính được chấm điểm SHAP: 876 cột
================================================================================

📋 TOP 50 CỘT CÓ ĐIỂM SHAP CAO NHẤT TỪ 5-FOLD CV:

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

                                         feature      mean_gain  mean_abs_shap
0                                EXT_SOURCE_MEAN  112244.736697       0.491528
1                                    CODE_GENDER    2481.160104       0.085117
2                          BUREAU_DEBT_RATIO_MAX    6293.018353       0.074687
3             PREV_DAYS_LAST_DUE_1ST_VERSION_MAX    3010.383031       0.071406
4                              CREDIT_TO_ANNUITY    7301.445893       0.068971
5                                    AMT_ANNUITY    3217.853413       0.068399
6                            NAME_EDUCATION_TYPE    3104.740696       0.066998
7                    INS_IS_PAYMENT_DELAYED_MEAN    4428.005551       0.064258
8                              ORGANIZATION_TYPE   10194.455316       0.063804
9                                   EXT_SOURCE_1    4422.943121       0.061462
10                         CREDIT_TO_GOODS_RATIO    5328.637557       0.057668
11                               OCCUPATION_TYPE    3754.070402       0.054200
12                            NAME_FAMILY_STATUS    1156.307265       0.054186
13                             GOODS_CREDIT_DIFF    3033.477258       0.051993
14                           INS_AMT_PAYMENT_SUM    2898.519768       0.048627
15                        INS_PAYMENT_RATIO_MEAN    3386.967823       0.048576
16                             ANNUITY_TO_INCOME    2262.068594       0.043784
17                   PREV_GOODS_CREDIT_RATIO_MAX    2223.905673       0.041196
18                          PREV_IS_REFUSED_MEAN    3669.867842       0.038774
19                  BUREAU_ACTIVE_DEBT_RATIO_MAX    3422.485663       0.033052
20                               EXT_SOURCE_PROD    5230.848633       0.031656
21                               AMT_GOODS_PRICE    1786.982640       0.031203
22                        ANNUITY_TO_GOODS_RATIO    2593.795237       0.030934
23                                EMPLOYED_YEARS    1941.562147       0.030386
24                                  EXT_SOURCE_2    1966.480297       0.028666
25                                 DAYS_EMPLOYED    2004.110053       0.026827
26                      PREV_APP_CREDIT_DIFF_MAX    1704.739116       0.025983
27                                    DAYS_BIRTH    2554.283310       0.025732
28                      CC_LIMIT_UTILIZATION_MAX    1271.765276       0.024975
29                              NAME_INCOME_TYPE     464.710723       0.020797
30  BUREAU_ACTIVE_DAYS_CREDIT_ENDDATE_CLEAN_MEAN    1204.212991       0.020769
31                        BUREAU_DEBT_RATIO_MEAN    1634.450996       0.020604
32                         EMPLOYED_TO_AGE_RATIO    1769.686894       0.018928
33                BUREAU_CREDIT_PAID_AMOUNT_MEAN    1222.095849       0.018358
34                                  EXT_SOURCE_3    2961.597460       0.018058
35                   POS_COMPLETION_TREND_6M_MAX     610.303321       0.016792
36            PREV_PLANNED_CONTRACT_DURATION_VAR    1479.731140       0.016754
37                                     AGE_YEARS    1759.124283       0.015874
38                         INS_PAYMENT_DELAY_VAR     879.215253       0.015771
39                  BUREAU_ACTIVE_DEBT_IS_NA_SUM    1142.672909       0.015610
40           PREV_LAST_DUE_1ST_VERSION_YEARS_MIN    1026.590158       0.015384
41                      DEF_30_CNT_SOCIAL_CIRCLE     684.881891       0.015287
42                 BUREAU_CREDIT_PAID_AMOUNT_SUM     964.185177       0.014884
43                      BUREAU_IS_LONG_TERM_MEAN     745.852576       0.014787
44                 BUREAU_CLOSED_DAYS_CREDIT_VAR    1000.217629       0.014758
45                        PREV_DAYS_LAST_DUE_MAX     708.602808       0.014469
46                        INS_PAYMENT_DELAY_MEAN    1143.419953       0.014083
47                  BUREAU_ACTIVE_PAID_RATIO_MAX    1084.637888       0.013936
48               PREV_DAYS_EARLY_TERMINATION_VAR    1282.330240       0.013735
49              CC_CNT_DRAWINGS_ATM_CURRENT_MEAN    1773.630719       0.013602

In [5]:
# --- INTEGRATED CELL: 5-FOLD CV SCREENING, SHAP RANKING & MASTER V3 EXPORT ---

import os
import time
import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import StratifiedKFold
import shap

start_time = time.time()
print("🚀 Bắt đầu quá trình 5-Fold CV Screening, SHAP Ranking và Xuất Dataset sạch...")

# 1. Nạp Master Dataset V2
v2_path = '/Users/nguyenminhtri/FinalYearPro/data/processed/master_train_dataset_v2.parquet'
v3_path = '/Users/nguyenminhtri/FinalYearPro/data/processed/master_train_dataset_v3.parquet'

print(f"⏳ Đang nạp Master Dataset V2 từ: {v2_path}")
df_master = pd.read_parquet(v2_path)

drop_cols = ['SK_ID_CURR', 'TARGET']
feature_cols = [c for c in df_master.columns if c not in drop_cols]

X = df_master[feature_cols].copy()
y = df_master['TARGET']

# Ép kiểu category cho toàn bộ cột chuỗi (string/object) để chống lỗi LightGBM
cat_cols = X.select_dtypes(include=['object', 'category', 'string']).columns.tolist()
if cat_cols:
    for col in cat_cols:
        X[col] = X[col].astype('category')

total_rows, total_cols = X.shape
print(f"📊 Dữ liệu đầu vào: {total_rows:,} dòng | {total_cols} thuộc tính")
print("-" * 80)

# 2. STEP 1: Khởi tạo & Huấn luyện 5-Fold CV để tính Mean Gain
N_SPLITS = 5
skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

feature_importances_gain = np.zeros(total_cols)

print("⏳ [STEP 1] Đang chạy 5-Fold CV để sàng lọc Feature Importance (Gain)...")
for fold, (train_idx, val_idx) in enumerate(skf.split(X, y), 1):
    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]

    model = lgb.LGBMClassifier(
        n_estimators=1000,
        learning_rate=0.05,
        num_leaves=31,
        random_state=42 + fold,
        n_jobs=-1,
        importance_type='gain'
    )

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=False)]
    )

    feature_importances_gain += model.feature_importances_ / N_SPLITS

# Bảng xếp hạng Gain
df_gain = pd.DataFrame({
    'feature': feature_cols,
    'mean_gain': feature_importances_gain
})

useful_features = df_gain[df_gain['mean_gain'] > 0]['feature'].tolist()
zero_importance_cols = df_gain[df_gain['mean_gain'] == 0]['feature'].tolist()

print(f"✅ Số cột CÓ ĐÓNG GÓP (Gain > 0) : {len(useful_features):,} cột")
print(f"❌ Số cột NHIỄU / THỪA (Gain == 0): {len(zero_importance_cols):,} cột")
print("-" * 80)

# 3. STEP 2: Tính TreeSHAP trên tập cột sạch (Gain > 0)
print(f"⏳ [STEP 2] Đang tính TreeSHAP Values trên {len(useful_features)} cột có Gain > 0...")
X_filtered = X[useful_features].copy()
shap_importances_mean = np.zeros(len(useful_features))

for fold, (train_idx, val_idx) in enumerate(skf.split(X_filtered, y), 1):
    X_train, y_train = X_filtered.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X_filtered.iloc[val_idx], y.iloc[val_idx]

    model_clean = lgb.LGBMClassifier(
        n_estimators=1000,
        learning_rate=0.05,
        num_leaves=31,
        random_state=42 + fold,
        n_jobs=-1,
        importance_type='gain'
    )

    model_clean.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=False)]
    )

    X_val_sample = X_val.sample(n=min(3000, len(X_val)), random_state=42)
    explainer = shap.TreeExplainer(model_clean)
    shap_vals = explainer.shap_values(X_val_sample)

    if isinstance(shap_vals, list):
        shap_vals = shap_vals[1]

    shap_importances_mean += np.abs(shap_vals).mean(axis=0) / N_SPLITS

# Xuất file CSV điểm số xếp hạng SHAP
df_final_ranking = df_gain[df_gain['mean_gain'] > 0].copy().reset_index(drop=True)
df_final_ranking['mean_abs_shap'] = shap_importances_mean
df_final_ranking = df_final_ranking.sort_values('mean_abs_shap', ascending=False).reset_index(drop=True)

csv_ranking_path = '/Users/nguyenminhtri/FinalYearPro/data/processed/feature_ranking_5fold_shap.csv'
os.makedirs(os.path.dirname(csv_ranking_path), exist_ok=True)
df_final_ranking.to_csv(csv_ranking_path, index=False)

# 4. STEP 3: TỰ ĐỘNG DROP 154 CỘT NHIỄU & XUẤT FILE MASTER V3 DUY NHẤT
print("-" * 80)
print(f"✂️ [STEP 3] Đang tiến hành loại bỏ {len(zero_importance_cols)} cột nhiễu khỏi Master Dataset...")

df_master_clean = df_master.drop(columns=zero_importance_cols, errors='ignore')

os.makedirs(os.path.dirname(v3_path), exist_ok=True)
print(f"⏳ Đang lưu Master Dataset V3 sạch ra đĩa tại: {v3_path}")
df_master_clean.to_parquet(v3_path, compression='snappy', index=False)

exec_time = time.time() - start_time
print("=" * 80)
print(f"🎉 HOÀN TẤT TOÀN BỘ QUY TRÌNH TRONG: {exec_time:.2f} GIÂY")
print(f"💾 File xếp hạng điểm số SHAP đã lưu : {csv_ranking_path}")
print(f"💾 File Master Dataset V3 sạch đã lưu : {v3_path}")
print(
    f"📊 Kích thước bảng Master V3 mới       : {df_master_clean.shape[0]:,} dòng | {df_master_clean.shape[1]} thuộc tính")
print(f"📉 Đã cắt giảm                         : {total_cols + len(drop_cols) - df_master_clean.shape[1]} cột nhiễu")
print("=" * 80)

# Hiển thị Top 50 cột có điểm SHAP cao nhất
display(df_final_ranking.head(50))

🚀 Bắt đầu quá trình 5-Fold CV Screening, SHAP Ranking và Xuất Dataset sạch...
⏳ Đang nạp Master Dataset V2 từ: /Users/nguyenminhtri/FinalYearPro/data/processed/master_train_dataset_v2.parquet
📊 Dữ liệu đầu vào: 307,511 dòng | 1030 thuộc tính
--------------------------------------------------------------------------------
⏳ [STEP 1] Đang chạy 5-Fold CV để sàng lọc Feature Importance (Gain)...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226148
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.190098 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 162742
[LightGBM] [Info] Number of data points in the train set: 246008, number of used features: 1029
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432482
[LightGBM] [Info] Start training from score -2.432482
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.139766 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 162696
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 1029
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.197302 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 162665
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 1029
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.177703 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 162755
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 1029
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.156565 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 162703
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 1029
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
✅ Số cột CÓ ĐÓNG GÓP (Gain > 0) : 876 cột
❌ Số cột NHIỄU / THỪA (Gain == 0): 154 cột
--------------------------------------------------------------------------------
⏳ [STEP 2] Đang tính TreeSHAP Values trên 876 cột có Gain > 0...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226148
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.114403 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 157525
[LightGBM] [Info] Number of data points in the train set: 246008, number of used features: 876
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432482
[LightGBM] [Info] Start training from score -2.432482

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.141286 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 157499
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 876
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.132237 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 157467
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 876
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.146538 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 157546
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 876
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.154314 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 157500
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 876
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

--------------------------------------------------------------------------------
✂️ [STEP 3] Đang tiến hành loại bỏ 154 cột nhiễu khỏi Master Dataset...
⏳ Đang lưu Master Dataset V3 sạch ra đĩa tại: /Users/nguyenminhtri/FinalYearPro/data/processed/master_train_dataset_v3.parquet
================================================================================
🎉 HOÀN TẤT TOÀN BỘ QUY TRÌNH TRONG: 383.77 GIÂY
💾 File xếp hạng điểm số SHAP đã lưu : /Users/nguyenminhtri/FinalYearPro/data/processed/feature_ranking_5fold_shap.csv
💾 File Master Dataset V3 sạch đã lưu : /Users/nguyenminhtri/FinalYearPro/data/processed/master_train_dataset_v3.parquet
📊 Kích thước bảng Master V3 mới       : 307,511 dòng | 878 thuộc tính
📉 Đã cắt giảm                         : 154 cột nhiễu
================================================================================

                                         feature      mean_gain  mean_abs_shap
0                                EXT_SOURCE_MEAN  112244.736697       0.491530
1                                    CODE_GENDER    2481.160104       0.085116
2                          BUREAU_DEBT_RATIO_MAX    6293.018353       0.074687
3             PREV_DAYS_LAST_DUE_1ST_VERSION_MAX    3010.383031       0.071416
4                              CREDIT_TO_ANNUITY    7301.445893       0.068975
5                                    AMT_ANNUITY    3217.853413       0.068345
6                            NAME_EDUCATION_TYPE    3104.740696       0.066997
7                    INS_IS_PAYMENT_DELAYED_MEAN    4428.005551       0.064255
8                              ORGANIZATION_TYPE   10194.455316       0.063804
9                                   EXT_SOURCE_1    4422.943121       0.061462
10                         CREDIT_TO_GOODS_RATIO    5328.637557       0.057684
11                               OCCUPATION_TYPE    3754.070402       0.054201
12                            NAME_FAMILY_STATUS    1156.307265       0.054188
13                             GOODS_CREDIT_DIFF    3033.477258       0.051991
14                           INS_AMT_PAYMENT_SUM    2898.519768       0.048585
15                        INS_PAYMENT_RATIO_MEAN    3386.967823       0.048579
16                             ANNUITY_TO_INCOME    2262.068594       0.043793
17                   PREV_GOODS_CREDIT_RATIO_MAX    2223.905673       0.041194
18                          PREV_IS_REFUSED_MEAN    3669.867842       0.038774
19                  BUREAU_ACTIVE_DEBT_RATIO_MAX    3422.485663       0.033052
20                               EXT_SOURCE_PROD    5230.848633       0.031658
21                               AMT_GOODS_PRICE    1786.982640       0.031199
22                        ANNUITY_TO_GOODS_RATIO    2593.795237       0.030934
23                                EMPLOYED_YEARS    1941.562147       0.030385
24                                  EXT_SOURCE_2    1966.480297       0.028662
25                                 DAYS_EMPLOYED    2004.110053       0.026827
26                      PREV_APP_CREDIT_DIFF_MAX    1704.739116       0.025981
27                                    DAYS_BIRTH    2554.283310       0.025731
28                      CC_LIMIT_UTILIZATION_MAX    1271.765276       0.024980
29                              NAME_INCOME_TYPE     464.710723       0.020783
30  BUREAU_ACTIVE_DAYS_CREDIT_ENDDATE_CLEAN_MEAN    1204.212991       0.020782
31                        BUREAU_DEBT_RATIO_MEAN    1634.450996       0.020604
32                         EMPLOYED_TO_AGE_RATIO    1769.686894       0.018927
33                BUREAU_CREDIT_PAID_AMOUNT_MEAN    1222.095849       0.018357
34                                  EXT_SOURCE_3    2961.597460       0.018057
35                   POS_COMPLETION_TREND_6M_MAX     610.303321       0.016793
36            PREV_PLANNED_CONTRACT_DURATION_VAR    1479.731140       0.016754
37                                     AGE_YEARS    1759.124283       0.015873
38                         INS_PAYMENT_DELAY_VAR     879.215253       0.015772
39                  BUREAU_ACTIVE_DEBT_IS_NA_SUM    1142.672909       0.015610
40           PREV_LAST_DUE_1ST_VERSION_YEARS_MIN    1026.590158       0.015383
41                      DEF_30_CNT_SOCIAL_CIRCLE     684.881891       0.015287
42                 BUREAU_CREDIT_PAID_AMOUNT_SUM     964.185177       0.014887
43                 BUREAU_CLOSED_DAYS_CREDIT_VAR    1000.217629       0.014759
44                      BUREAU_IS_LONG_TERM_MEAN     745.852576       0.014752
45                        PREV_DAYS_LAST_DUE_MAX     708.602808       0.014468
46                        INS_PAYMENT_DELAY_MEAN    1143.419953       0.014083
47                  BUREAU_ACTIVE_PAID_RATIO_MAX    1084.637888       0.013940
48               PREV_DAYS_EARLY_TERMINATION_VAR    1282.330240       0.013735
49              CC_CNT_DRAWINGS_ATM_CURRENT_MEAN    1773.630719       0.013602

In [7]:
# --- INTEGRATED CELL: 5-FOLD CV SCREENING, SHAP RANKING & MASTER V4 CLEAN EXPORT ---

import os
import time
import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import StratifiedKFold
import shap

start_time = time.time()
print("🚀 Bắt đầu quá trình 5-Fold CV Screening, SHAP Ranking và Xuất Master V4 Clean...")

# 1. Đường dẫn file nạp vào và xuất ra
input_path = '/Users/nguyenminhtri/FinalYearPro/data/processed/master_train_dataset_v4.parquet'
output_clean_path = '/Users/nguyenminhtri/FinalYearPro/data/processed/master_train_dataset_v4_clean.parquet'

print(f"⏳ Đang nạp Master Dataset V4 từ: {input_path}")
df_master = pd.read_parquet(input_path)

drop_cols = ['SK_ID_CURR', 'TARGET']
feature_cols = [c for c in df_master.columns if c not in drop_cols]

X = df_master[feature_cols].copy()
y = df_master['TARGET']

# Ép kiểu category cho toàn bộ cột chuỗi (string/object) để LightGBM xử lý tối ưu
cat_cols = X.select_dtypes(include=['object', 'category', 'string']).columns.tolist()
if cat_cols:
    for col in cat_cols:
        X[col] = X[col].astype('category')

total_rows, total_cols = X.shape
print(f"📊 Dữ liệu đầu vào: {total_rows:,} dòng | {total_cols} thuộc tính")
print("-" * 80)

# 2. STEP 1: Khởi tạo & Huấn luyện 5-Fold CV để tính Mean Gain
N_SPLITS = 5
skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)

feature_importances_gain = np.zeros(total_cols)

print("⏳ [STEP 1] Đang chạy 5-Fold CV để sàng lọc Feature Importance (Gain)...")
for fold, (train_idx, val_idx) in enumerate(skf.split(X, y), 1):
    X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]

    model = lgb.LGBMClassifier(
        n_estimators=1000,
        learning_rate=0.05,
        num_leaves=31,
        random_state=42 + fold,
        n_jobs=-1,
        importance_type='gain'
    )

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=False)]
    )

    feature_importances_gain += model.feature_importances_ / N_SPLITS

# Bảng xếp hạng Gain
df_gain = pd.DataFrame({
    'feature': feature_cols,
    'mean_gain': feature_importances_gain
})

useful_features = df_gain[df_gain['mean_gain'] > 0]['feature'].tolist()
zero_importance_cols = df_gain[df_gain['mean_gain'] == 0]['feature'].tolist()

print(f"✅ Số cột CÓ ĐÓNG GÓP (Gain > 0) : {len(useful_features):,} cột")
print(f"❌ Số cột NHIỄU / THỪA (Gain == 0): {len(zero_importance_cols):,} cột")
print("-" * 80)

# 3. STEP 2: Tính TreeSHAP trên tập cột sạch (Gain > 0)
print(f"⏳ [STEP 2] Đang tính TreeSHAP Values trên {len(useful_features)} cột có Gain > 0...")
X_filtered = X[useful_features].copy()
shap_importances_mean = np.zeros(len(useful_features))

for fold, (train_idx, val_idx) in enumerate(skf.split(X_filtered, y), 1):
    X_train, y_train = X_filtered.iloc[train_idx], y.iloc[train_idx]
    X_val, y_val = X_filtered.iloc[val_idx], y.iloc[val_idx]

    model_clean = lgb.LGBMClassifier(
        n_estimators=1000,
        learning_rate=0.05,
        num_leaves=31,
        random_state=42 + fold,
        n_jobs=-1,
        importance_type='gain'
    )

    model_clean.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=False)]
    )

    X_val_sample = X_val.sample(n=min(3000, len(X_val)), random_state=42)
    explainer = shap.TreeExplainer(model_clean)
    shap_vals = explainer.shap_values(X_val_sample)

    if isinstance(shap_vals, list):
        shap_vals = shap_vals[1]

    shap_importances_mean += np.abs(shap_vals).mean(axis=0) / N_SPLITS

# Tạo bảng hiển thị SHAP (không lưu ra file CSV)
df_final_ranking = df_gain[df_gain['mean_gain'] > 0].copy().reset_index(drop=True)
df_final_ranking['mean_abs_shap'] = shap_importances_mean
df_final_ranking = df_final_ranking.sort_values('mean_abs_shap', ascending=False).reset_index(drop=True)

# 4. STEP 3: TỰ ĐỘNG DROP CÁC CỘT NHIỄU & XUẤT FILE MASTER V4 SẠCH
print("-" * 80)
print(f"✂️ [STEP 3] Đang tiến hành loại bỏ {len(zero_importance_cols)} cột nhiễu khỏi Master Dataset...")

df_master_clean = df_master.drop(columns=zero_importance_cols, errors='ignore')

os.makedirs(os.path.dirname(output_clean_path), exist_ok=True)
print(f"⏳ Đang lưu Master Dataset V4 sạch ra đĩa tại: {output_clean_path}")
df_master_clean.to_parquet(output_clean_path, compression='snappy', index=False)

exec_time = time.time() - start_time
print("=" * 80)
print(f"🎉 HOÀN TẤT TOÀN BỘ QUY TRÌNH TRONG: {exec_time:.2f} GIÂY")
print(f"💾 File Master Dataset V4 sạch đã lưu : {output_clean_path}")
print(f"📊 Kích thước bảng Master V4 Clean    : {df_master_clean.shape[0]:,} dòng | {df_master_clean.shape[1]} thuộc tính")
print(f"📉 Đã cắt giảm                        : {len(zero_importance_cols)} cột nhiễu")
print("=" * 80)

# Hiển thị Top 50 cột có điểm SHAP cao nhất trên notebook
display(df_final_ranking.head(50))

🚀 Bắt đầu quá trình 5-Fold CV Screening, SHAP Ranking và Xuất Master V4 Clean...
⏳ Đang nạp Master Dataset V4 từ: /Users/nguyenminhtri/FinalYearPro/data/processed/master_train_dataset_v4.parquet
📊 Dữ liệu đầu vào: 307,511 dòng | 1041 thuộc tính
--------------------------------------------------------------------------------
⏳ [STEP 1] Đang chạy 5-Fold CV để sàng lọc Feature Importance (Gain)...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226148
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.173885 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 164633
[LightGBM] [Info] Number of data points in the train set: 246008, number of used features: 1040
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432482
[LightGBM] [Info] Start training from score -2.432482
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.191959 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 164588
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 1040
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.226635 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 164552
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 1040
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.170290 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 164669
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 1040
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.220889 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 164609
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 1040
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486
✅ Số cột CÓ ĐÓNG GÓP (Gain > 0) : 902 cột
❌ Số cột NHIỄU / THỪA (Gain == 0): 139 cột
--------------------------------------------------------------------------------
⏳ [STEP 2] Đang tính TreeSHAP Values trên 902 cột có Gain > 0...
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226148
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.157534 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 160254
[LightGBM] [Info] Number of data points in the train set: 246008, number of used features: 902
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432482
[LightGBM] [Info] Start training from score -2.432482

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.168090 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 160232
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 902
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.168371 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 160195
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 902
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.196664 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 160303
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 902
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 19860, number of negative: 226149
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.141750 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 160249
[LightGBM] [Info] Number of data points in the train set: 246009, number of used features: 902
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.080729 -> initscore=-2.432486
[LightGBM] [Info] Start training from score -2.432486

/Users/nguyenminhtri/FinalYearPro/venv/lib/python3.13/site-packages/shap/explainers/_tree.py:632: UserWarning: LightGBM binary classifier with TreeExplainer shap values output has changed to a list of ndarray
  warnings.warn(

--------------------------------------------------------------------------------
✂️ [STEP 3] Đang tiến hành loại bỏ 139 cột nhiễu khỏi Master Dataset...
⏳ Đang lưu Master Dataset V4 sạch ra đĩa tại: /Users/nguyenminhtri/FinalYearPro/data/processed/master_train_dataset_v4_clean.parquet
================================================================================
🎉 HOÀN TẤT TOÀN BỘ QUY TRÌNH TRONG: 416.69 GIÂY
💾 File Master Dataset V4 sạch đã lưu : /Users/nguyenminhtri/FinalYearPro/data/processed/master_train_dataset_v4_clean.parquet
📊 Kích thước bảng Master V4 Clean    : 307,511 dòng | 904 thuộc tính
📉 Đã cắt giảm                        : 139 cột nhiễu
================================================================================

                                         feature      mean_gain  mean_abs_shap
0                                EXT_SOURCE_MEAN  112333.048635       0.489782
1                                    CODE_GENDER    2535.248502       0.085438
2                          BUREAU_DEBT_RATIO_MAX    6327.265509       0.076007
3             PREV_DAYS_LAST_DUE_1ST_VERSION_MAX    3127.956589       0.074173
4                              CREDIT_TO_ANNUITY    7226.731169       0.070061
5                                    AMT_ANNUITY    3312.176153       0.068535
6                            NAME_EDUCATION_TYPE    3128.533528       0.067651
7                              ORGANIZATION_TYPE   10651.244981       0.065253
8                    INS_IS_PAYMENT_DELAYED_MEAN    4497.289970       0.065197
9                                   EXT_SOURCE_1    4473.696437       0.061960
10                             GOODS_CREDIT_DIFF    3162.546134       0.056098
11                            NAME_FAMILY_STATUS    1135.901499       0.055414
12                         CREDIT_TO_GOODS_RATIO    5249.123900       0.054068
13                               OCCUPATION_TYPE    3688.219141       0.052644
14                        INS_PAYMENT_RATIO_MEAN    3367.214598       0.049444
15                           INS_AMT_PAYMENT_SUM    2842.063275       0.049030
16                   PREV_GOODS_CREDIT_RATIO_MAX    2152.862483       0.044662
17                             ANNUITY_TO_INCOME    2196.211737       0.044231
18                          PREV_IS_REFUSED_MEAN    3855.722505       0.039395
19                               EXT_SOURCE_PROD    5576.750570       0.032991
20                  BUREAU_ACTIVE_DEBT_RATIO_MAX    3381.254611       0.032137
21                                  EXT_SOURCE_2    2088.974611       0.031087
22                               AMT_GOODS_PRICE    1869.663160       0.030102
23                                 DAYS_EMPLOYED    2115.275668       0.029916
24                                EMPLOYED_YEARS    1952.930327       0.028887
25                        ANNUITY_TO_GOODS_RATIO    2553.936311       0.028180
26                      PREV_APP_CREDIT_DIFF_MAX    1721.973779       0.026029
27                      CC_LIMIT_UTILIZATION_MAX    1280.973383       0.025196
28                                    DAYS_BIRTH    2663.312255       0.024515
29                              NAME_INCOME_TYPE     483.522044       0.022544
30                        BUREAU_DEBT_RATIO_MEAN    1630.557466       0.019897
31                BUREAU_CREDIT_PAID_AMOUNT_MEAN    1366.738461       0.019623
32  BUREAU_ACTIVE_DAYS_CREDIT_ENDDATE_CLEAN_MEAN    1252.905076       0.019169
33                         EMPLOYED_TO_AGE_RATIO    1673.611285       0.018990
34                                  EXT_SOURCE_3    3159.777624       0.018480
35            PREV_PLANNED_CONTRACT_DURATION_VAR    1575.227250       0.018288
36                      BUREAU_IS_LONG_TERM_MEAN     795.136043       0.017201
37                                     AGE_YEARS    1680.668482       0.016957
38                   POS_COMPLETION_TREND_6M_MAX     677.859378       0.016914
39                  BUREAU_ACTIVE_DEBT_IS_NA_SUM    1082.318840       0.016109
40           PREV_LAST_DUE_1ST_VERSION_YEARS_MIN    1106.118752       0.016005
41                        PREV_DAYS_LAST_DUE_MAX     763.800992       0.015389
42                         INS_PAYMENT_DELAY_VAR     826.751534       0.015223
43                 BUREAU_CREDIT_PAID_AMOUNT_SUM    1016.675126       0.015034
44                  BUREAU_ACTIVE_PAID_RATIO_MAX    1257.510527       0.015016
45                      DEF_30_CNT_SOCIAL_CIRCLE     639.092032       0.014607
46                        INS_PAYMENT_DELAY_MEAN    1049.646442       0.014518
47          BUREAU_CLOSED_DAYS_CREDIT_UPDATE_MAX     747.413346       0.014052
48                      INS_IS_PAYMENT_EARLY_SUM    1092.060867       0.013731
49                       PREV_IS_SHORT_TERM_MEAN     834.631645       0.013726